services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run dev:api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: whiteboard_db

  realtime:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run dev:realtime
    depends_on:
      - app
    environment:
      HOST: '0.0.0.0'
      PORT: '1234'
      Y_PERSISTENCE: 'y-postgresql'
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: myuser
      PG_PASSWORD: mypassword
      PG_DATABASE: whiteboard_db
      
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: whiteboard_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: