services:
  realtime:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run dev:realtime
    environment:
      HOST: '0.0.0.0'
      PORT: '1234'